name: ddobaki_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.0
  fl_chart: ^0.63.0
  share_plus: ^7.2.1
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  js: ^0.6.7
  # 음성 녹음 기능에 필요한 패키지지
  flutter_sound: ^9.2.13
  permission_handler: ^11.0.1
  http: ^0.13.6
  path_provider: ^2.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpg
